### ISSUE TITLE
Minor error in sixth homework

### ISSUE THREAD

**Issue by kubicon** [JuliaTeachingCTU/Scientific-Programming-in-Julia#28]
In homework from week 6, there semms to be a problem with the assignment itself [https://github.com/JuliaTeachingCTU/Scientific-Programming-in-Julia/blob/master/docs/src/lecture_06/hw.md](https://github.com/JuliaTeachingCTU/Scientific-Programming-in-Julia/blob/master/docs/src/lecture_06/hw.md). 
There is line:

> return an array of unique alphabetically sorted symbols representing variables in an expression.

However next to it is example
`[:x, :y, :z, :c]`
Which is not alphabetically sorted

**Comment by janfrancu** [comment]
Thanks for filling the issue. It should be fixed now.
