### ISSUE TITLE
Lab06 sreplace_i

### ISSUE THREAD

**Issue by Vojtasii** [JuliaTeachingCTU/Scientific-Programming-in-Julia#34]
Hi, I have a I think correct solution for the string replacement, in case you wish to add it.

```Julia
sreplace_i(s) = replace(s, r"([^\w]|\b)i(?=[^\w]|\z)" => s"\1k")
```
It replaces "i" only if it is not preceded or followed by an alphanumeric character or there is an end/beginning of string.

example:
```Julia
s = "i + i*i + y*i - sin(z) + int(i) + i"
sreplace_i(s)

"k + k*k + y*k - sin(z) + int(k) + k"
```

**Comment by janfrancu** [comment]
Thanks for the issue, I will look into it.

**Comment by janfrancu** [comment]
I have not found any obvious edge cases, therefore I have added just after the naive solution.
