### ISSUE TITLE
autodiff

### ISSUE THREAD

**Issue by pevnak** [JuliaTeachingCTU/Scientific-Programming-in-Julia#98]
It's really:
code-rewriting vs operator overloading.
and
Implict vs explict tape.
See:
Yota: explict tape, code-rewriting
Tracker: implict tape, operator overloading
ReverseDiff: explict tape, operator overloading
Zygote: implict tape, code-rewriting

**Comment by nmheim** [comment]
I am looking forward to your in depth explanation about this;)
